### ISSUE TITLE
New design implementation

### ISSUE THREAD

**Issue by raysummee** [Megabyte-143/certified_cliche#15]
#### Description:

The design we're currently using is not going with our flow. (for flow read the readme file). 
So we need to implement the new design.
We'll add multiple sub task, for better maintaining

Figma Link: [click here](https://www.figma.com/file/HjYi7KbugT0xsXoA7arIN2/Untitled?node-id=0%3A1)

#### Sub-task

**Pages names (refer to Figma file)**
- [ ] 1. select role
- [ ] 3. home page/ 7. transferred certificate
- [ ] 5. events/ 8. transferred certificate - events
- [ ] 4. home page: select a certificate
- [ ] 6. create certificate

**Components**
- [ ] Navbar + tabs
- [ ] Footer

Please start with the components first, because every page uses it.
Don't redundant the common elements.

If you want I can make more sub-task or update the task.

**Comment by Rajdip019** [comment]
Can I start working on this? @raysummee

**Comment by raysummee** [comment]
first complete #17 which is assigned to you. This issue (#15) is very large so I divided it into sub task. After completing #17 you can start working on others sub tasks too.
